name: Bump Tag Version
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: 'minor'
      - name: Compile Release Notes
        uses: csexton/fictional-release-note-compiler@dne
        id: notes
      - name: Create Release
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.notes.outputs.body }}

