name: Release

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}  # this secret is pre-provided for the workflow and does not
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Release Job
        uses: BigWigsMods/packager@master
